# Generated by Django 4.2.6 on 2023-11-14 03:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='created by')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('last_updated_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='created by')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
            options={
                'abstract': False,
            },
            bases=(main.models.SlugModelMixin, models.Model),
        ),
    ]
