# Generated by Django 4.2.6 on 2023-11-14 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='created by')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('last_updated_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='created by')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('FEMALE', 'F'), ('MALE', 'M'), ('OTHER', 'O')], default='O', verbose_name='gender')),
                ('contact_number', models.CharField(default='', max_length=100, verbose_name='contact number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('hire_date', models.DateTimeField(verbose_name='hire date')),
                ('specialization', models.CharField(max_length=100, verbose_name='specialization')),
                ('identification', models.CharField(max_length=100, verbose_name='identification')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_staff_set', to='facility.facility', verbose_name='facility')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_user_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
