# Generated by Django 4.2.6 on 2024-01-04 03:55

from django.db import migrations, models
import report.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_alter_patient_last_updated_by'),
        ('device', '0004_alter_device_last_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='created by')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('last_updated_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='last updated by')),
                ('file', models.FileField(blank=True, null=True, upload_to=report.utils.upload_to, verbose_name='file')),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end datetime')),
                ('status', models.CharField(choices=[('FAILED', 'Failed'), ('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful')], default='Pending', verbose_name='status')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('patients', models.ManyToManyField(related_name='patient_record_report_set', to='patient.patient', verbose_name='patients')),
                ('variables', models.ManyToManyField(related_name='variable_record_report_set', to='device.variable', verbose_name='variables')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
