# Generated by Django 4.2.6 on 2024-01-04 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_last_updated_by'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordreport',
            name='patients',
        ),
        migrations.AddField(
            model_name='recordreport',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_record_report_set', to='patient.patient', verbose_name='patient'),
        ),
    ]
