# Generated by Django 4.2.6 on 2023-12-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='manufacturer'),
        ),
    ]
