# Generated by Django 4.2.6 on 2024-01-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_devicetype_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='last updated by'),
        ),
    ]
