# Generated by Django 4.2.6 on 2024-02-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='identifier',
            field=models.CharField(max_length=100, null=True, verbose_name='identifier'),
        ),
    ]
