# Generated by Django 4.2.6 on 2024-02-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_variable_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='identifier',
            field=models.CharField(max_length=100, unique=True, verbose_name='identifier'),
        ),
    ]
