# Generated by Django 4.2.6 on 2024-02-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_variable_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='css_class_suffix',
            field=models.CharField(default='temp', max_length=100, verbose_name='css class suffix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='icon',
            field=models.CharField(default='icon', max_length=100, verbose_name='icon'),
            preserve_default=False,
        ),
    ]
