# Generated by Django 4.2.6 on 2023-12-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_checked',
            field=models.BooleanField(null=True),
        ),
    ]
