# Generated by Django 4.2.6 on 2023-11-14 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='created by')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('last_updated_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='created by')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('identification', models.CharField(max_length=100, verbose_name='identification')),
                ('admission_date', models.DateTimeField(verbose_name='admission date')),
                ('discharge_date', models.DateTimeField(null=True, verbose_name='discharge date')),
                ('gender', models.CharField(choices=[('FEMALE', 'F'), ('MALE', 'M'), ('OTHER', 'O')], default='O', verbose_name='gender')),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DECEASED', 'Deceased'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='Admitted', verbose_name='status')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('contact_number', models.CharField(default='', max_length=100, verbose_name='contact number')),
                ('emergency_contact_name', models.CharField(default='', max_length=100, verbose_name='emergency contact name')),
                ('emergency_contact_number', models.CharField(default='', max_length=100, verbose_name='emergency contact number')),
                ('alarm_settings', models.ManyToManyField(related_name='alarm_settings_patient_set', to='monitoring.alarmsettings', verbose_name='alarm settings')),
                ('attending_staff', models.ManyToManyField(related_name='staff_patient_set', to='staff.staff', verbose_name='attending staff')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_patient_set', to='facility.facility', verbose_name='facility')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_user_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
