# Generated by Django 4.2.6 on 2023-12-11 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_alarmsettings_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_alter_staff_date_of_birth_alter_staff_email_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='alarm_settings',
            field=models.ManyToManyField(blank=True, related_name='alarm_settings_patient_set', to='monitoring.alarmsettings', verbose_name='alarm settings'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='attending_staff',
            field=models.ManyToManyField(blank=True, related_name='staff_patient_set', to='staff.staff', verbose_name='attending staff'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='discharge date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_user_set', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
