# Generated by Django 4.2.6 on 2024-02-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=100, null=True, verbose_name='age'),
        ),
    ]
