# Generated by Django 4.2.6 on 2023-11-14 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('device', '0002_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_record_set', to='patient.patient', verbose_name='patient'),
        ),
        migrations.AddField(
            model_name='record',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_record_set', to='device.variable', verbose_name='variable'),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_alarm_settings_set', to='device.variable', verbose_name='variable'),
        ),
    ]
