# Generated by Django 4.2.6 on 2023-12-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettings',
            name='operator',
            field=models.CharField(choices=[('E', 'E'), ('GT', 'GT'), ('GTE', 'GTE'), ('LT', 'LT'), ('LTE', 'LTE')], verbose_name='operator'),
        ),
    ]
