# Generated by Django 4.2.6 on 2024-01-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_alarmsettings_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettings',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='record',
            name='alarm_name',
            field=models.CharField(blank=True, default='', verbose_name="alarm's name"),
        ),
        migrations.AlterField(
            model_name='record',
            name='alarm_operator',
            field=models.CharField(blank=True, choices=[('E', 'E'), ('GT', 'GT'), ('GTE', 'GTE'), ('LT', 'LT'), ('LTE', 'LTE')], default='', verbose_name="alarm's operator"),
        ),
        migrations.AlterField(
            model_name='record',
            name='alarm_ref_value',
            field=models.FloatField(blank=True, null=True, verbose_name='reference value'),
        ),
        migrations.AlterField(
            model_name='record',
            name='alarm_settings_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_settings_record_set', to='monitoring.alarmsettings', verbose_name='alarm settings'),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='last updated by'),
        ),
    ]
